### ISSUE TITLE
Consider replacing gitkit

### ISSUE THREAD

**Issue by prologic** [icyphox/legit#12]
With code borrowed from [gitreposerver](https://github.com/seankhliao/gitreposerver), which removes the external dependency on the `git` cli.

**Comment by icyphox** [comment]
Hey thanks for this, TIL that I can do this natively in go-git. I’ll play around with it today.

**Comment by prologic** [comment]
> Hey thanks for this, TIL that I can do this natively in go-git. I’ll play around with it today.

I beat you to it 😅 -- no SSH support though. But that can come later...

**Comment by prologic** [comment]
Oh And no push support yet either.
