### ISSUE TITLE
Missing proper copyright notice and license

### ISSUE THREAD

**Issue by Exagone313** [icyphox/legit#2]
The *readme* states that the project is licensed under the MIT License, however the terms are not included, neither is the copyright notice. The project might still be proprietary.

You can get the full license text [here](https://opensource.org/licenses/MIT) and put it in a *license* or *copying* file, make sure to include your name and the year you started the project in the copyright notice.

NB: You can also consider using the [ISC License](https://opensource.org/licenses/ISC), which uses newer language than the MIT license or even the [Unlicense](https://unlicense.org/), which is equivalent to public domain, depending to your choices.

**Comment by icyphox** [comment]
Hey there, thanks. I was too lazy to add the full file, and figured simply mentioning the license would be fine. Nevertheless, I've added the full license text as I've done in my other projects.

**Comment by Exagone313** [comment]
The year is still missing 😅 (Only the year the project started really matters apparently tough IANAL)
