### ISSUE TITLE
Supporting subpath

### ISSUE THREAD

**Issue by ratsclub** [icyphox/legit#27]
I tried to do some reverse-proxy magic but couldn't find a way to have `legit` under a subpath, such as: `https://example.com/git/<repo>`. Is there something I'm missing?

**Comment by icyphox** [comment]
Hi, I don't (immediately) see why it wouldn't be possible. Can you perhaps share your config for whatever reverse proxy you're using so I can test it out when I have a minute?

**Comment by ratsclub** [comment]
Oh, I'm sorry, I did make it work somehow. It was my fault, indeed.

Thanks!
