### ISSUE TITLE
go-import tags don't work as expected for bare repos with .git suffix

### ISSUE THREAD

**Issue by wbrijesh** [icyphox/legit#34]
I like using legit a lot, but every time I want a git server I end up rewriting some parts of legit to use with [soft-serve](https://github.com/charmbracelet/soft-serve)

The only issue is legit expects bare repositories without .git in their name and soft-serve expects .git, this is fine at first but it causes issues with go-import meta tag which doesn't work

I could just use legit without soft-serve but user management is a hassle without soft-serve,
Soft serve also has go-import tags built it but it doesn't have a web gui

I think using .git suffix is not required but common with bare repos, if you can fix this legit along with soft serve would be the perfect combination.

**Comment by icyphox** [comment]
Any reason you can't have your reverse proxy of choice rewrite your paths with the .git suffix? Seems like a weird change to make in legit, since nothing is preventing you from having your bare repos have .git in the name on the filesystem.

**Comment by wbrijesh** [comment]
I hadn't thought of that, thanks
