### ISSUE TITLE
Proposal for adding archive endpoints to refs

### ISSUE THREAD

**Issue by gabrielgio** [icyphox/legit#37]
Hello,

I'd like to know if you are interested in adding an endpoint to return tar files.

I would add something like:

```
	mux.HandleFunc("GET /{name}/archive/{ref...}", d.Archive)
```

It would return a `.tar.gz` file from this following example:

```bash
curl https://git.icyphox.sh/legit/archive/v0.2.2.tar.gz -o /dev/null
```

The `archive` is placeholder let me know if want a different path.

For the ui (like in this page[^1]) I'd add `tar.gz` next to `browse` and `log`

For the implementation I'd do an in-memory implementation, so no storage would
be required.

Let me know if you are interested and I can submit the patch myself :smile: 

[^1]: https://git.icyphox.sh/legit/refs

**Comment by icyphox** [comment]
Hi! Thanks for writing this up! I really like this, and would gladly accept a patch. :)
