### ISSUE TITLE
New bare repo doesn't appear in listing

### ISSUE THREAD

**Issue by yonas** [icyphox/legit#4]
I created a bare repo as mentioned in #3, but it doesn't show up under http://git.lan:5555/

**Comment by icyphox** [comment]
Are you able to provide some more info? Do you see anything in the logs? What does your config look like? And your directory structure? 

It’s hard to say otherwise.

**Comment by icyphox** [comment]
I tried this with the repository you linked in #3 (https://github.com/zyedidia/micro), and wasn't able to reproduce it—it shows up just fine. I'm going to guess it's an issue with your setup.

**Comment by icyphox** [comment]
Closing as this seems like user/setup error and lacking enough info. Feel free to reopen if you have anything more to add.
