### ISSUE TITLE
Proper Docker Images

### ISSUE THREAD

**Issue by datashard** [icyphox/legit#46]
Would it be possible to publish official docker images? I've been wanting to set this up but can't get it to run nicely in my Coolify Setup (it runs just fine when i do `docker compose up -d` locally)

**Comment by icyphox** [comment]
Yeah it should be possible to whip up a quick CI job for that. Happy to accept a patch if this is needed at short notice!

**Comment by icyphox** [comment]
This is now available: https://github.com/icyphox/legit/pkgs/container/legit

**Comment by datashard** [comment]
Thank you so much!
