### ISSUE TITLE
Pushing to new bare repo returns no pushing allowed 400 error

### ISSUE THREAD

**Issue by yonas** [icyphox/legit#5]
```
$ git push
remote: no pushing allowed!
fatal: unable to access 'http://git.lan:5555/micro/': The requested URL returned error: 400
```

**Comment by icyphox** [comment]
Hi there, this is mentioned in the readme:

> Pushing over https, while supported, is disabled because auth is a pain. Use ssh.

I don’t intend to change this behaviour since I don’t need it. Patches welcome.

**Comment by yonas** [comment]
> Pushing over https, while supported, is disabled ...

How about unencrypted http?
